### ISSUE TITLE
User Cancel out of FileOpenDialog fails

### ISSUE THREAD

**Issue by GCuser99** [fafalone/LinebreakRepair#1]
Thanks for this tool Jon. In Command2_Click event handler, if user hits Cancel in FileOpenDialog, then throws an error. I worked-around by swapping these two lines from:
```vba
.Show Me.hWnd
On Error Resume Next
```
to:
```vba
On Error Resume Next
.Show Me.hWnd
```

Thanks!

**Comment by fafalone** [comment]
Oops yeah meant to have it on that line. Thanks.

Fixed in v1.0.2, all files and binaries updated.
