### ISSUE TITLE
my code 

### ISSUE THREAD

**Issue by xxdoc** [fafalone/LinebreakRepair#2]
https://github.com/xxdoc/gitub

 Set fin = fs.OpenTextFile(SourceDir & Name)
    temp = fin.ReadAll
    Set fout = fs.CreateTextFile(TargetDir & Name, True)
    '    Open TargetDir & Name For Output As #1
    '    Print #1, fin.ReadAll
    '    Close
    
    temp = Replace(temp, Chr(13) & Chr(10), Chr(10))
    temp = Replace(temp, Chr(13), Chr(10))
    
    fout.Write Replace(temp, Chr(10), Chr(13) & Chr(10))
    fin.Close

    fout.Close

**Comment by fafalone** [comment]
Yeah I considered using simpler i/o and VB string handling... I guess I just don't trust it to not have locale issues or reliability issues, and personally prefer file APIs anyway. Definitely don't like the FileSystemObject. Just preference really.
